In [7]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('tweets.csv', sep=';', on_bad_lines='skip',
                   lineterminator='\n', low_memory=False)
data

,id,user,fullname,url,timestamp,replies,likes,retweets,text\r
0,1.132977e+18,KamdemAbdiel,Abdiel kamdem,NaN,2019-05-27 11:49:14+00,0,0,0,È appena uscito un nuovo video! LES CRYPTOMONN...
1,1.132977e+18,bitcointe,Bitcointe,NaN,2019-05-27 11:49:18+00,0,0,0,Cardano: Digitize Currencies; EOS https://t.co...
2,1.132977e+18,3eyedbran,Bran - 3 Eyed Raven,NaN,2019-05-27 11:49:06+00,0,2,1,Another Test tweet that wasn't caught in the s...
3,1.132977e+18,DetroitCrypto,J. Scardina,NaN,2019-05-27 11:49:22+00,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\n...
4,1.132977e+18,mmursaleen72,Muhammad Mursaleen,NaN,2019-05-27 11:49:23+00,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NO...
...,...,...,...,...,...,...,...,...,...
16889760,1.198262e+18,JacobCanfield,Jacob Canfield,NaN,2019-11-23 15:28:50+00,2,16,3,Happy #FibonacciDay \n\nA while back I created...
16889761,1.198266e+18,Vizique,Vizique,NaN,2019-11-23 15:45:55+00,0,0,0,Bitcoin Suisse Certificates :) https://t.co/nd...
16889762,1.198266e+18,torusJKL,Gal Buki ($torusJKL),NaN,2019-11-23 15:45:56+00,0,0,0,Register now for the early access of the Codug...
16889763,1.198266e+18,Adekunl95628158,Adekunle Daniel,NaN,2019-11-23 15:45:57+00,0,0,0,@btc \n@btc \nDo you know that BTC Baskets isn...
16889764,1.198266e+18,HaraldoXRP,Harry,NaN,2019-11-23 15:45:06+00,0,2,1,$BTC - an update on the longer term view for B...

In [13]:
data = data[['timestamp', 'text\r']]
data.rename(columns={'timestamp': 'date', 'text\r': 'text'}, inplace=True)
data

,date,text
0,2019-05-27 11:49:14+00,È appena uscito un nuovo video! LES CRYPTOMONN...
1,2019-05-27 11:49:18+00,Cardano: Digitize Currencies; EOS https://t.co...
2,2019-05-27 11:49:06+00,Another Test tweet that wasn't caught in the s...
3,2019-05-27 11:49:22+00,Current Crypto Prices! \n\nBTC: $8721.99 USD\n...
4,2019-05-27 11:49:23+00,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NO...
...,...,...
16889760,2019-11-23 15:28:50+00,Happy #FibonacciDay \n\nA while back I created...
16889761,2019-11-23 15:45:55+00,Bitcoin Suisse Certificates :) https://t.co/nd...
16889762,2019-11-23 15:45:56+00,Register now for the early access of the Codug...
16889763,2019-11-23 15:45:57+00,@btc \n@btc \nDo you know that BTC Baskets isn...
16889764,2019-11-23 15:45:06+00,$BTC - an update on the longer term view for B...

In [29]:
data.isna().sum()

date    0
text    0
dtype: int64

In [37]:
from datetime import datetime


data.date = np.array([datetime.strptime(d.split('+')[0],
                                        '%Y-%m-%d %H:%M:%S')
                      for d in data.date])

In [41]:
def check_skipped_days():
    x = 0
    arr = np.array([])
    day_before = datetime.now()
    index_before = 0

    for index, d in enumerate(data.date):
        diff = 0

        if x == 0:
            day_before, index_before = d, index
            x+=1
            continue

        diff = (d - day_before).days

        if diff > 1:
            arr = np.append(arr, '{} => {} : {} days'.format(index_before, index, diff))

        day_before, index_before = d, index

    return arr

In [42]:
skipped_days = check_skipped_days()

print(skipped_days)
len(skipped_days)

['12 => 13 : 4 days' '15 => 16 : 16 days' '21 => 22 : 3763 days' ...
 '16889683 => 16889684 : 10 days' '16889704 => 16889705 : 2 days'
 '16889753 => 16889754 : 5 days']

144982

In [43]:
print(data.date.min())
print(data.date.max())
print((data.date.max() - data.date.min()).days)

2007-04-19 07:14:38
2019-11-23 15:45:57
4601