In [1]:
import numpy as np
import pandas as pd

In [2]:
data = pd.read_csv('tweets.csv', sep=';', on_bad_lines='skip',
                   lineterminator='\n', low_memory=False)
data

,id,user,fullname,url,timestamp,replies,likes,retweets,text\r
0,1.132977e+18,KamdemAbdiel,Abdiel kamdem,NaN,2019-05-27 11:49:14+00,0,0,0,È appena uscito un nuovo video! LES CRYPTOMONN...
1,1.132977e+18,bitcointe,Bitcointe,NaN,2019-05-27 11:49:18+00,0,0,0,Cardano: Digitize Currencies; EOS https://t.co...
2,1.132977e+18,3eyedbran,Bran - 3 Eyed Raven,NaN,2019-05-27 11:49:06+00,0,2,1,Another Test tweet that wasn't caught in the s...
3,1.132977e+18,DetroitCrypto,J. Scardina,NaN,2019-05-27 11:49:22+00,0,0,0,Current Crypto Prices! \n\nBTC: $8721.99 USD\n...
4,1.132977e+18,mmursaleen72,Muhammad Mursaleen,NaN,2019-05-27 11:49:23+00,0,0,0,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NO...
...,...,...,...,...,...,...,...,...,...
16889760,1.198262e+18,JacobCanfield,Jacob Canfield,NaN,2019-11-23 15:28:50+00,2,16,3,Happy #FibonacciDay \n\nA while back I created...
16889761,1.198266e+18,Vizique,Vizique,NaN,2019-11-23 15:45:55+00,0,0,0,Bitcoin Suisse Certificates :) https://t.co/nd...
16889762,1.198266e+18,torusJKL,Gal Buki ($torusJKL),NaN,2019-11-23 15:45:56+00,0,0,0,Register now for the early access of the Codug...
16889763,1.198266e+18,Adekunl95628158,Adekunle Daniel,NaN,2019-11-23 15:45:57+00,0,0,0,@btc \n@btc \nDo you know that BTC Baskets isn...
16889764,1.198266e+18,HaraldoXRP,Harry,NaN,2019-11-23 15:45:06+00,0,2,1,$BTC - an update on the longer term view for B...

In [3]:
data = data[['timestamp', 'text\r']]
data = data.rename(columns={'timestamp': 'date', 'text\r': 'text'})
data

,date,text
0,2019-05-27 11:49:14+00,È appena uscito un nuovo video! LES CRYPTOMONN...
1,2019-05-27 11:49:18+00,Cardano: Digitize Currencies; EOS https://t.co...
2,2019-05-27 11:49:06+00,Another Test tweet that wasn't caught in the s...
3,2019-05-27 11:49:22+00,Current Crypto Prices! \n\nBTC: $8721.99 USD\n...
4,2019-05-27 11:49:23+00,Spiv (Nosar Baz): BITCOIN Is An Asset &amp; NO...
...,...,...
16889760,2019-11-23 15:28:50+00,Happy #FibonacciDay \n\nA while back I created...
16889761,2019-11-23 15:45:55+00,Bitcoin Suisse Certificates :) https://t.co/nd...
16889762,2019-11-23 15:45:56+00,Register now for the early access of the Codug...
16889763,2019-11-23 15:45:57+00,@btc \n@btc \nDo you know that BTC Baskets isn...
16889764,2019-11-23 15:45:06+00,$BTC - an update on the longer term view for B...

In [4]:
data.isna().sum()

date    0
text    0
dtype: int64

In [5]:
from datetime import datetime

data.date = np.array(
    [datetime.strptime(d.split(' ')[0], '%Y-%m-%d') for d in data.date])

In [6]:
data.sort_values(by='date', inplace=True)
data.reset_index(drop=True, inplace=True)
data

               date                                               text
0        2007-04-19  is happily mugging at BTC where she will hook ...
1        2009-01-11                                  Running bitcoin\r
2        2009-01-21  Looking at ways to add more anonymity to bitco...
3        2009-01-27  Thinking about how to reduce CO2 emissions fro...
4        2009-01-29  From: Satoshi Nakamoto - 2009-01-11 22:32 Bitc...
...             ...                                                ...
16889760 2019-11-23  Bitcoin:$7231.27732436\nEthereum:$150.48909214...
16889761 2019-11-23  BTC\n\nfinexの乖離がまだ異常水域です。\n\nペナントの収束タイミングに合わせた...
16889762 2019-11-23  #BTC New Hub, we have relaunch our #NEWYORKCOI...
16889763 2019-11-23  トランザクション収入がまともにないBitcoinさんのマイナーは単価に依存するからこうなるん...
16889764 2019-11-23  $BTC - an update on the longer term view for B...

[16889765 rows x 2 columns]

In [7]:
def check_skipped_days():
    x = 0
    arr = np.array([])
    day_before = datetime.now()
    index_before = 0

    for index, d in enumerate(data.date):
        diff = 0

        if x == 0:
            day_before, index_before = d, index
            x+=1
            continue

        diff = (d - day_before).days

        if diff > 1:
            arr = np.append(arr, '{} => {} : {} days'.format(index_before, index, diff))

        day_before, index_before = d, index

    return arr

In [8]:
skipped_days = check_skipped_days()

print(skipped_days)
len(skipped_days)

['0 => 1 : 633 days' '1 => 2 : 10 days' '2 => 3 : 6 days'
 '3 => 4 : 2 days' '4 => 5 : 20 days' '5 => 6 : 111 days'
 '6 => 7 : 10 days' '10 => 11 : 96 days' '11 => 12 : 71 days'
 '12 => 13 : 9 days' '14 => 15 : 88 days' '15 => 16 : 50 days'
 '16 => 17 : 50 days' '17 => 18 : 30 days' '21 => 22 : 24 days'
 '22 => 23 : 2 days' '23 => 24 : 5 days' '24 => 25 : 62 days'
 '25 => 26 : 9 days' '26 => 27 : 6 days' '27 => 28 : 19 days'
 '28 => 29 : 4 days' '30 => 31 : 2 days' '31 => 32 : 5 days'
 '35 => 36 : 3 days' '36 => 37 : 5 days' '37 => 38 : 4 days'
 '38 => 39 : 9 days' '39 => 40 : 3 days' '40 => 41 : 8 days'
 '41 => 42 : 35 days' '42 => 43 : 42 days' '43 => 44 : 18 days'
 '44 => 45 : 2 days' '45 => 46 : 6 days' '46 => 47 : 2 days'
 '47 => 48 : 2 days' '48 => 49 : 3 days' '51 => 52 : 11 days'
 '53 => 54 : 2 days' '78 => 79 : 3 days' '82 => 83 : 2 days'
 '86 => 87 : 2 days' '150 => 151 : 2 days' '158 => 159 : 5 days'
 '165 => 166 : 2 days' '167 => 168 : 6 days' '168 => 169 : 3 days'
 '169 => 170 : 2 days' '170 => 171 : 2 days' '171 => 172 : 4 days'
 '176 => 177 : 6 days' '178 => 179 : 5 days' '179 => 180 : 5 days'
 '181 => 182 : 3 days' '182 => 183 : 8 days' '183 => 184 : 4 days'
 '184 => 185 : 2 days' '185 => 186 : 2 days' '186 => 187 : 12 days'
 '187 => 188 : 4 days' '188 => 189 : 9 days' '189 => 190 : 4 days'
 '191 => 192 : 2 days' '192 => 193 : 3 days' '193 => 194 : 9 days'
 '195 => 196 : 8 days' '197 => 198 : 2 days' '198 => 199 : 6 days'
 '199 => 200 : 15 days' '200 => 201 : 5 days' '201 => 202 : 5 days'
 '202 => 203 : 7 days' '205 => 206 : 19 days' '206 => 207 : 15 days']

75

In [9]:
data = data.loc[207:]
data.reset_index(drop=True, inplace=True)

In [10]:
skipped_days = check_skipped_days()

print(skipped_days)
len(skipped_days)

[]

0

In [11]:
print(data.date.min())
print(data.date.max())
print((data.date.max() - data.date.min()).days)

2011-12-30 00:00:00
2019-11-23 00:00:00
2885